In [19]:
import numpy as np 

## 1.DataTypes & Attributes

In [20]:
# Numpy's main datatype is ndarray (n-dimensional array)
arr1 = np.array([1,2,3])
arr1 

array([1, 2, 3])

In [21]:
arr2 = np.array([[1,2,3],[4,5,6]])
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [22]:
arr3 = np.array([[[1.0,2,3],[4,5,6],[7,8,9]], [[1,2,3],[4,5,6],[7,8,9]]])
arr3

array([[[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]],

       [[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]]])

In [23]:
arr1.shape, arr2.shape, arr3.shape

((3,), (2, 3), (2, 3, 3))

In [24]:
arr1.ndim, arr2.ndim, arr3.ndim

(1, 2, 3)

In [25]:
arr1.dtype, arr2.dtype, arr3.dtype

(dtype('int64'), dtype('int64'), dtype('float64'))

In [26]:
# Total number of elements we have in total
arr1.size, arr2.size, arr3.size

(3, 6, 18)

In [27]:
# Create a DataFrame from a NumPy array
import pandas as pd 
df = pd.DataFrame(arr2)
df

0  1  2
0  1  2  3
1  4  5  6

## 2. Creating arrays

In [28]:
sample_array = np.array([1,2,3])
sample_array

array([1, 2, 3])

In [29]:
sample_array.dtype

dtype('int64')

In [30]:
ones = np.ones((2,3), dtype=int)
ones, ones.dtype

(array([[1, 1, 1],
        [1, 1, 1]]),
 dtype('int64'))

In [31]:
zeros = np.zeros((3,2), dtype=int)
zeros, zeros.dtype

(array([[0, 0],
        [0, 0],
        [0, 0]]),
 dtype('int64'))

In [32]:
random_array_1 = np.random.randint(low=0, high=10, size=(3,5))
random_array_1, random_array_1.size, random_array_1.ndim, random_array_1.dtype

(array([[6, 7, 7, 8, 1],
        [5, 9, 8, 9, 4],
        [3, 0, 3, 5, 0]]),
 15,
 2,
 dtype('int64'))

In [33]:
random_array_2 = np.random.random(size=(5,3))
random_array_2, random_array_2.size, random_array_2.ndim, random_array_2.dtype

(array([[0.97861834, 0.79915856, 0.46147936],
        [0.78052918, 0.11827443, 0.63992102],
        [0.14335329, 0.94466892, 0.52184832],
        [0.41466194, 0.26455561, 0.77423369],
        [0.45615033, 0.56843395, 0.0187898 ]]),
 15,
 2,
 dtype('float64'))

In [34]:
random_array_3 = np.random.rand(5,3)
random_array_3, random_array_3.size, random_array_3.ndim, random_array_3.dtype

(array([[0.6176355 , 0.61209572, 0.616934  ],
        [0.94374808, 0.6818203 , 0.3595079 ],
        [0.43703195, 0.6976312 , 0.06022547],
        [0.66676672, 0.67063787, 0.21038256],
        [0.1289263 , 0.31542835, 0.36371077]]),
 15,
 2,
 dtype('float64'))

In [36]:
# Pseudo-random numbers ... using seed
np.random.seed(42)
random_array_4 = np.random.randint(10, size=(5,3))
random_array_4

array([[6, 3, 7],
       [4, 6, 9],
       [2, 6, 7],
       [4, 3, 7],
       [7, 2, 5]])

## 3. Viewing arrays and matrices

In [37]:
np.unique(random_array_4)

array([2, 3, 4, 5, 6, 7, 9])

In [39]:
# Get the first 4 numbers of the inner most arrays 
arr4 = np.random.randint(10, size=(2,3,4,5))

# The indexing is thought to be from inner to outter side.
# i.e., 5 elements inside 4 vectors, inside 3 vectors, that it is inside 2 other vectors.
arr4

array([[[[9, 8, 4, 5, 3],
         [9, 6, 8, 6, 0],
         [0, 8, 8, 3, 8],
         [2, 6, 5, 7, 8]],

        [[4, 0, 2, 9, 7],
         [5, 7, 8, 3, 0],
         [0, 9, 3, 6, 1],
         [2, 0, 4, 0, 7]],

        [[0, 0, 1, 1, 5],
         [6, 4, 0, 0, 2],
         [1, 4, 9, 5, 6],
         [3, 6, 7, 0, 5]]],


       [[[7, 4, 3, 1, 5],
         [5, 0, 8, 5, 2],
         [3, 3, 2, 9, 2],
         [2, 3, 6, 3, 8]],

        [[0, 7, 6, 1, 7],
         [0, 8, 8, 1, 6],
         [9, 2, 6, 9, 8],
         [3, 0, 1, 0, 4]],

        [[4, 6, 8, 8, 2],
         [2, 2, 3, 7, 5],
         [7, 0, 7, 3, 0],
         [7, 3, 5, 7, 3]]]])

In [40]:
arr4[:,:,:,:4]

array([[[[9, 8, 4, 5],
         [9, 6, 8, 6],
         [0, 8, 8, 3],
         [2, 6, 5, 7]],

        [[4, 0, 2, 9],
         [5, 7, 8, 3],
         [0, 9, 3, 6],
         [2, 0, 4, 0]],

        [[0, 0, 1, 1],
         [6, 4, 0, 0],
         [1, 4, 9, 5],
         [3, 6, 7, 0]]],


       [[[7, 4, 3, 1],
         [5, 0, 8, 5],
         [3, 3, 2, 9],
         [2, 3, 6, 3]],

        [[0, 7, 6, 1],
         [0, 8, 8, 1],
         [9, 2, 6, 9],
         [3, 0, 1, 0]],

        [[4, 6, 8, 8],
         [2, 2, 3, 7],
         [7, 0, 7, 3],
         [7, 3, 5, 7]]]])

In [41]:
arr4[:, :, :, :1]

array([[[[9],
         [9],
         [0],
         [2]],

        [[4],
         [5],
         [0],
         [2]],

        [[0],
         [6],
         [1],
         [3]]],


       [[[7],
         [5],
         [3],
         [2]],

        [[0],
         [0],
         [9],
         [3]],

        [[4],
         [2],
         [7],
         [7]]]])

## 4.Manipulating & comparing arrays

In [42]:
# Broadcasting documentation. Important to have a look
# PS: // means floor division. It removevs the decimals (round down)