In [1]:
import numpy as np 

## 1.DataTypes & Attributes

In [6]:
# Numpy's main datatype is ndarray (n-dimensional array)
arr1 = np.array([1,2,3])
arr1 

array([1, 2, 3])

In [3]:
arr2 = np.array([[1,2,3],[4,5,6]])
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [10]:
arr3 = np.array([[[1.0,2,3],[4,5,6],[7,8,9]], [[1,2,3],[4,5,6],[7,8,9]]])
arr3

array([[[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]],

       [[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]]])

In [11]:
arr1.shape, arr2.shape, arr3.shape

((3,), (2, 3), (2, 3, 3))

In [12]:
arr1.ndim, arr2.ndim, arr3.ndim

(1, 2, 3)

In [13]:
arr1.dtype, arr2.dtype, arr3.dtype

(dtype('int64'), dtype('int64'), dtype('float64'))

In [14]:
# Total number of elements we have in total
arr1.size, arr2.size, arr3.size

(3, 6, 18)

In [17]:
# Create a DataFrame from a NumPy array
import pandas as pd 
df = pd.DataFrame(arr2)
df

0  1  2
0  1  2  3
1  4  5  6

## 2. Creating arrays

In [18]:
sample_array = np.array([1,2,3])
sample_array

array([1, 2, 3])

In [19]:
sample_array.dtype

dtype('int64')

In [26]:
ones = np.ones((2,3), dtype=int)
ones, ones.dtype

(array([[1, 1, 1],
        [1, 1, 1]]),
 dtype('int64'))

In [30]:
zeros = np.zeros((3,2), dtype=int)
zeros, zeros.dtype

(array([[0, 0],
        [0, 0],
        [0, 0]]),
 dtype('int64'))

In [42]:
random_array_1 = np.random.randint(low=0, high=10, size=(3,5))
random_array_1, random_array_1.size, random_array_1.ndim, random_array_1.dtype

(array([[1, 7, 7, 9, 0],
        [5, 8, 7, 9, 8],
        [9, 6, 0, 3, 8]]),
 15,
 2,
 dtype('int64'))

In [43]:
random_array_2 = np.random.random(size=(5,3))
random_array_2, random_array_2.size, random_array_2.ndim, random_array_2.dtype

(array([[0.74239488, 0.98049352, 0.17462985],
        [0.75310676, 0.82824685, 0.43311121],
        [0.28460427, 0.67464915, 0.61977568],
        [0.58018404, 0.14415284, 0.06843846],
        [0.75605812, 0.80035023, 0.99963353]]),
 15,
 2,
 dtype('float64'))

In [44]:
random_array_3 = np.random.rand(5,3)
random_array_3, random_array_3.size, random_array_3.ndim, random_array_3.dtype

(array([[0.86711849, 0.42320956, 0.54590333],
        [0.14604408, 0.87158663, 0.80138291],
        [0.41050767, 0.59799597, 0.83711184],
        [0.84636757, 0.1202054 , 0.20028167],
        [0.30045962, 0.19253044, 0.60806016]]),
 15,
 2,
 dtype('float64'))

In [41]:
# Pseudo-random numbers ... using seed